import getCurrentUser from "./actions/getCurrentUser";
import Layout from "./components/Layout/Layout";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="ja">
      <Layout currentUser={currentUser}>{children}</Layout>
    </html>
  );
}
